### ISSUE TITLE
video streaming ?

### ISSUE THREAD

**Issue by din2011** [Icelain/radio#1]
can u do for video streaming ?

**Comment by Icelain** [comment]
I'd recommend looking into [RTMP](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol) and it's Go implementation [Go-RTMP](https://github.com/yutopp/go-rtmp) if you want something that works directly out of the box without needing to develop your own client.

NOTE: Technically, you can stream anything you want over HTTP. So, if you can replace the audio file with a video file, adjust buffer sizes accordingly in main.go, and implement a client which can read the video and display the chunks properly, you can stream video directly over HTTP.
